const test=require('node:test'),assert=require('node:assert/strict');
let A;try{A=require('../site/analytics.js');}catch{A={};}
const stats=overrides=>({points:0,fgm:0,fga:0,threeMade:0,threeAttempts:0,ftm:0,fta:0,offensive:0,defensive:0,rebounds:0,assists:0,steals:0,blocks:0,turnovers:0,fouls:0,...overrides});
const p=(id,count,s)=>({player_id:id,player_name:id,jersey_number:1,played_count:count,played_ms:count?60000:0,stats:stats(s)});
const game=(date,category='official')=>({game_id:date,game_date:date,category,home_points:80,away_points:70,coverage:'complete',players:[]});
test('season boundaries label January and leap February with prior Fall year',()=>{assert.equal(typeof A.season,'function');for(const [date,want] of [['2026-02-28','fall:2025'],['2026-03-01','spring:2026'],['2026-07-31','spring:2026'],['2026-08-01','fall:2026'],['2027-02-28','fall:2026'],['2028-02-29','fall:2027']])assert.equal(A.season(date),want);});
test('period and category filters intersect without moving Jan/Feb into wrong calendar year',()=>{assert.equal(typeof A.filterGames,'function');const games=[game('2026-07-31'),game('2026-08-01','friendly'),game('2027-02-01'),game('2026-11-01',null)];assert.deepEqual(A.filterGames(games,{period:'fall:2026',category:'all'}).map(g=>g.game_date),['2026-08-01','2027-02-01','2026-11-01']);assert.equal(A.filterGames(games,{period:'year:2026',category:'all'}).length,3);assert.equal(A.filterGames(games,{period:'career',category:'friendly'}).length,1);assert.equal(A.filterGames(games,{period:'career',category:'official'}).length,2);});
test('averages count zero-stat appearances but exclude DNP and use weighted shooting',()=>{assert.equal(typeof A.summarize,'function');const games=[{...game('2026-09-01'),players:[p('P1',1,{points:10,fgm:5,fga:5}),p('P2',0,{})]},{...game('2026-09-02'),players:[p('P1',1,{fga:15}),p('P2',1,{})]}];const s=A.summarize({roster:[{player_id:'P1',player_name:'Current name',jersey_number:8}]},games);const player=s.players.find(p=>p.player_id==='P1');assert.equal(player.appearances,2);assert.equal(player.averages.points,5);assert.equal(player.shooting.fg,25);assert.equal(player.player_name,'Current name');assert.equal(s.players.find(p=>p.player_id==='P2').appearances,1);});
test('possession estimates, overtime pace and efficiency use explicit complete data',()=>{assert.equal(typeof A.gameMetrics,'function');const g={...game('2026-09-01'),stats_complete:true,duration_ms:2700000,home_stats:stats({points:80,fga:60,offensive:10,turnovers:12,fta:20}),away_stats:stats({points:70,fga:58,offensive:8,turnovers:14,fta:10})};const m=A.gameMetrics(g);assert.ok(Math.abs(m.possessions-69.6)<1e-9);assert.ok(Math.abs(m.pace-61.8666666667)<1e-8);assert.ok(Math.abs(m.offensiveRating-114.9425287356)<1e-8);assert.equal(A.gameMetrics({...g,stats_complete:false}).possessions,null);assert.equal(A.gameMetrics({...g,duration_ms:null}).pace,null);assert.equal(A.gameMetrics({...g,away_stats:null}).defensiveRating,null);});
test('leaders expose ties, omit zero and guest leaders, and rank rates by actual appearances',()=>{assert.equal(typeof A.leaders,'function');const players=[{player_id:'P1',appearances:2,stats:stats({rebounds:8})},{player_id:'P2',appearances:1,stats:stats({rebounds:8})},{player_id:'P_GUEST',appearances:1,stats:stats({rebounds:30})}];assert.deepEqual(A.leaders(players,'rebounds','total').players.map(p=>p.player_id),['P1','P2']);assert.deepEqual(A.leaders(players,'rebounds','average').players.map(p=>p.player_id),['P2']);assert.equal(A.leaders(players,'steals','total').players.length,0);});
test('empty data never produces NaN, infinity, or fictitious opponent box scores',()=>{assert.equal(typeof A.summarize,'function');const s=A.summarize({roster:[]},[]);assert.equal(s.ppg,null);assert.equal(s.advanced.pace,null);assert.equal(s.shooting.fg,null);const old=A.summarize({roster:[]},[game('2026-09-01')]);assert.equal(old.away,null);assert.equal(old.advanced.eligible,0);assert.equal(old.ppg,80);});
test('aggregate pace weights duration and ratings weight possessions, with eligible counts',()=>{assert.equal(typeof A.summarize,'function');const g={...game('2026-09-01'),stats_complete:true,duration_ms:2400000,home_stats:stats({fga:50}),away_stats:stats({fga:50})};const s=A.summarize({},[g,{...g,game_id:'two',duration_ms:1200000,home_points:20,away_points:30,home_stats:stats({fga:25}),away_stats:stats({fga:25})},{...game('2026-09-03')}]);assert.equal(s.advanced.eligible,2);assert.equal(s.advanced.paceEligible,2);assert.equal(s.advanced.pace,50);assert.ok(Math.abs(s.advanced.offensiveRating-133.3333333333)<1e-8);assert.equal(s.away,null);});
test('partial minutes are labeled and missing minutes remain unavailable',()=>{assert.equal(typeof A.summarize,'function');const g={...game('2026-09-01'),coverage:'partial',players:[{...p('P1',1,{}),played_ms:null}]};const player=A.summarize({},[g]).players[0];assert.equal(player.played_ms,null);assert.equal(player.partial,true);});
test('guest group per-game averages count games, not the number of guests',()=>{const g={...game('2026-09-01'),players:[p('P_GUEST',2,{points:20})]};const player=A.summarize({},[g]).players[0];assert.equal(player.appearances,1);assert.equal(player.averages.points,20);});
test('DNP zero minutes cannot turn unknown played minutes into a recorded zero',()=>{const games=[{...game('2026-09-01'),players:[p('P1',0,{})]},{...game('2026-09-02'),coverage:'partial',players:[{...p('P1',1,{}),played_ms:null}]}];const player=A.summarize({},games).players[0];assert.equal(player.played_ms,null);assert.equal(player.appearances,1);assert.equal(player.partial,true);});
