const {test}=require('node:test');
const assert=require('node:assert/strict');
const E=require('../src/engine.js'),T=require('../src/team.js');
const fs=require('node:fs');
const A=fs.existsSync(require('node:path').join(__dirname,'../src/player-analytics.js'))?require('../src/player-analytics.js'):{};
function fixture(){const roster=Array.from({length:7},(_,i)=>({id:'P'+i,name:'Player '+i,number:i,...(i>4?{guest:true}:{})}));const g=E.createGame({date:'2026-09-26',opponent:'Away',minutes:10,overtimeMinutes:5},roster);T.configure(g,roster.map(p=>p.id),roster.slice(0,5).map(p=>p.id));E.start(g,0);return g;}
test('snapshots retain the original five across equal-time substitutions and guests',()=>{const g=fixture();const e=E.recordEvent(g,'3PT_MADE',g.roster[0],'HOME',0);E.pause(g,0);T.substitute(g,['P0','P1','P2','P5','P6']);const a=E.recordEvent(g,'2PT_MADE',null,'AWAY',0);assert.deepEqual(e.lineupSnapshot.playerIds,['P0','P1','P2','P3','P4']);assert.deepEqual(a.lineupSnapshot.playerIds,['P0','P1','P2','P5','P6']);assert.equal(A.player(g,'P0').plusMinus,1);assert.equal(A.player(g,'P3').plusMinus,3);assert.equal(A.player(g,'P5').plusMinus,-2);});
test('shooting and efficiency use active counts and unavailable denominators',()=>{const g=fixture();for(const [type,n] of [['3PT_MADE',2],['3PT_MISSED',3],['2PT_MADE',2],['2PT_MISSED',3],['FT_MADE',3],['FT_MISSED',1],['ASSIST',6],['TURNOVER',2]])for(let i=0;i<n;i++)E.recordEvent(g,type,g.roster[0],'HOME',0);const s=A.player(g,'P0');assert.equal(s.fgPct,40);assert.equal(s.threePct,40);assert.equal(s.ftPct,75);assert.equal(s.efgPct,50);assert.ok(Math.abs(s.tsPct-55.27210884353742)<1e-10);assert.equal(s.astTo,3);assert.equal(A.player(g,'P1').fgPct,null);assert.equal(A.player(g,'P1').astTo,null);assert.match(A.csv(g),/plus_minus_status/);});
test('missing historical lineups never claim exact zero plus-minus',()=>{const g=fixture();const e=E.recordEvent(g,'2PT_MADE',null,'AWAY',0);delete e.lineupSnapshot;assert.equal(A.player(g,'P0').plusMinus,null);assert.equal(A.player(g,'P0').plusMinusStatus,'unknown');e.is_voided=true;assert.equal(A.player(g,'P0').plusMinus,0);});
test('backup rejects malformed lineup snapshots',()=>{const g=fixture();E.recordEvent(g,'ASSIST',g.roster[0],'HOME',0).lineupSnapshot={status:'complete',playerIds:['P0','P0','P1','P2','P3']};E.pause(g,0);assert.throws(()=>E.validateState({version:2,roster:g.roster,games:[g],currentGameId:g.id}));});
module.exports={fixture};
