const test=require('node:test'),assert=require('node:assert/strict');
const R=require('../src/remote.js');
const E=require('../src/engine.js'),T=require('../src/team.js');
function game(){const roster=Array.from({length:5},(_,i)=>({id:'P_'+i,name:'Player '+i,number:i}));const g=E.createGame({date:'2026-09-08',opponent:'Hawks',minutes:10,overtimeMinutes:5},roster);T.configure(g,roster.map(p=>p.id),roster.map(p=>p.id));E.start(g,100);E.pause(g,1100);g.finished=true;return g;}
test('only completed games prepare upload',()=>{const g=game();g.finished=false;assert.throws(()=>R.prepare(g,E,T),/finish/i);});
test('retry retains exact participation revision even after another CSV export',()=>{const g=game(),a=R.prepare(g,E,T);T.participationCSV(g);const b=R.prepare(g,E,T);assert.deepEqual(a,b);assert.equal(g.remote.state,'pending');});
test('CSV round trips quoted Unicode and multiline fields',()=>{const rows=[{name:'牛,"a"\nnext',value:'0'}];assert.deepEqual(R.parseCSV(R.csv(['name','value'],rows)).rows,rows);});
test('request rejects HTTP errors with status and keeps upload payload',async()=>{const g=game(),payload=R.prepare(g,E,T);const c=new R.Client('https://api.example',async()=>({ok:false,status:503,json:async()=>({error:'Database unavailable'})}));await assert.rejects(c.upload(payload),e=>e.status===503);assert.deepEqual(g.remote.payload,payload);});
test('client sends bearer role token and exact bundle',async()=>{let seen;const c=new R.Client('https://api.example/',async(url,options)=>{seen={url,options};return {ok:true,status:200,json:async()=>({game_id:'G1'})};});c.token='session';const result=await c.upload({finished:true});assert.equal(result.game_id,'G1');assert.equal(seen.url,'https://api.example/api/games');assert.equal(seen.options.headers.Authorization,'Bearer session');assert.equal(seen.options.body,'{"finished":true}');});
test('mixed content and URL credentials are rejected',()=>{assert.throws(()=>new R.Client('https://user:pass@example.com'),/URL/i);assert.throws(()=>new R.Client('http://example.com'),/HTTPS/i);});
test('public aggregation uses participation appearances and excludes missing minutes',()=>{const snapshot={roster:[],games:[{home_points:2,away_points:0,coverage:'complete',players:[{player_id:'P1',player_name:'A',played_ms:60000,played_count:1,stats:{points:2,fgm:1,fga:1}}]},{home_points:0,away_points:0,coverage:'partial',players:[{player_id:'P1',player_name:'A',played_ms:30000,played_count:1,stats:{points:0}}]}]};const result=R.totals(snapshot);assert.equal(result.players[0].appearances,2);assert.equal(result.players[0].played_ms,90000);assert.equal(result.players[0].partial,true);assert.equal(result.players[0].stats.points,2);assert.equal(result.wins,1);assert.equal(result.ties,1);});

test('definitive validation rejection unlocks a never-accepted game',()=>{const g=game();R.prepare(g,E,T);R.failed(g,{status:400});assert.equal(g.remote,undefined);});
test('ambiguous failure preserves payload and remains locked across later validation errors',()=>{const g=game(),p=R.prepare(g,E,T);R.failed(g,Error('Connection lost'));assert.equal(g.remote.uncertain,true);R.failed(g,{status:400});assert.deepEqual(g.remote.payload,p);});
test('unknown total minutes remain null while mixed totals show known subtotal',()=>{const base={player_id:'P1',player_name:'A',played_count:1,stats:{}};const data={roster:[],games:[{home_points:0,away_points:0,coverage:'partial',players:[{...base,played_ms:null}]}]};assert.equal(R.totals(data).players[0].played_ms,null);data.games.push({home_points:0,away_points:0,coverage:'complete',players:[{...base,played_ms:60000}]});assert.equal(R.totals(data).players[0].played_ms,60000);assert.equal(R.totals(data).players[0].partial,true);});
